AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - script/**/*
    - bin/**/*
    - test/**/*
    - node_modules/**/*
    - Rakefile
    - config.ru
    - config/initializers/**/*
    - config/environments/**/*
    - config/queue_schema.rb
    - db/seeds.rb

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/jobs/**/*
