AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - script/**/*
    - bin/**/*
    - test/**/*
    # TEMP: app/models/structures is ignored temporarily for Rubocop.
    - app/models/structures/**/*
    - node_modules/**/*
    - Rakefile
    - config.ru
    - config/initializers/**/*
    - config/environments/**/*

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/jobs/**/*
