AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - script/**/*
    - bin/**/*
    - test/**/*
    - node_modules/**/*
    - Rakefile
    - config.ru
    - config/initializers/**/*
    - config/environments/**/*

    # TEMP: These files are ignored temporarily.
    - app/models/structures/**/*

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Exclude:
    # Routes are typically going to grow quite a lot
    - config/routes.rb
    # Seed generation can be complex. Its safe to ignore this rule for seeds.rb.
    - db/seeds.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/jobs/**/*
